source 'https://rubygems.org'

ruby "2.1.1"

gem 'rails', '4.1.5'
gem 'pg'
gem 'sdoc', '~> 0.4.0', group: :doc, require: false
gem 'spring',        group: :development

gem 'active_model_serializers'
gem 'thin'
gem 'quiet_assets'

group :production, :staging do
	gem 'rails_12factor'
end

